"""Analyzer registry: the set of questions this system can actually answer.

The design premise of SKILL sec. 28 is that the AI layer is *decision support*,
not chatbot search. So the unit of capability here is an **analyzer** - a named
function that answers one question with real queries and returns a structured
``Finding``.

That has three consequences worth stating plainly:

* **Numbers are never generated by a language model.** Every figure in an answer
  came out of the database. A model may later narrate a Finding, but it cannot
  invent one.
* **The system knows what it cannot answer.** An unmatched question returns the
  list of questions that *are* supported, instead of a confident guess.
* **Permissions are enforced before the analyzer runs**, by role and by scope,
  in one place.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import asdict, dataclass, field
from typing import Any

import frappe
from frappe import _
from frappe.utils import flt, now

from ags_edusmart.ags_ai.scope import Scope


@dataclass
class Driver:
	"""One contributor to a change, for explanatory answers (SKILL sec. 28.1)."""

	label: str
	current: float
	previous: float
	change: float
	change_percent: float
	# Share of the total movement this driver accounts for. This is what makes
	# an answer explanatory rather than merely descriptive.
	contribution_percent: float

	@property
	def direction(self) -> str:
		if self.change > 0:
			return "up"
		if self.change < 0:
			return "down"
		return "flat"


@dataclass
class Finding:
	"""The structured answer to one question."""

	code: str
	title: str
	headline: float | None = None
	unit: str = "Number"
	summary: str = ""
	rows: list[dict] = field(default_factory=list)
	drivers: list[Driver] = field(default_factory=list)
	# Populated by the registry, not the analyzer, so it cannot be forgotten.
	scope_description: str = ""
	as_of: str = ""
	# True when the underlying data was too thin to answer honestly.
	insufficient_data: bool = False
	notes: list[str] = field(default_factory=list)

	def to_dict(self) -> dict:
		payload = asdict(self)
		payload["drivers"] = [
			{**asdict(d), "direction": d.direction} for d in self.drivers
		]
		return payload


@dataclass
class Analyzer:
	code: str
	question: str
	category: str
	fn: Callable[..., Finding]
	keywords: tuple[str, ...]
	roles: tuple[str, ...]
	description: str = ""

	def may_run(self, scope: Scope) -> bool:
		if not self.roles:
			return True
		if "Administrator" in scope.roles or "System Manager" in scope.roles:
			return True
		return bool(set(self.roles) & scope.roles)


REGISTRY: dict[str, Analyzer] = {}


def analyzer(code: str, question: str, category: str, keywords: tuple[str, ...],
             roles: tuple[str, ...] = (), description: str = ""):
	"""Register one answerable question."""

	def wrap(fn: Callable[..., Finding]) -> Callable[..., Finding]:
		if code in REGISTRY:
			raise ValueError(f"duplicate analyzer code: {code}")
		REGISTRY[code] = Analyzer(
			code=code,
			question=question,
			category=category,
			fn=fn,
			keywords=keywords,
			roles=roles,
			description=description or (fn.__doc__ or "").strip().split("\n")[0],
		)
		return fn

	return wrap


def load_all() -> None:
	"""Import the insight modules so their decorators run."""
	from ags_edusmart.ags_ai.insights import (  # noqa: F401
		academic,
		collections,
		finance,
		hr,
		inventory,
		procurement,
	)


def all_analyzers(scope: Scope | None = None) -> list[Analyzer]:
	load_all()
	items = sorted(REGISTRY.values(), key=lambda a: (a.category, a.code))
	if scope is None:
		return items
	return [a for a in items if a.may_run(scope)]


def get(code: str) -> Analyzer:
	load_all()
	if code not in REGISTRY:
		frappe.throw(_("Unknown analysis: {0}").format(code))
	return REGISTRY[code]


def run(code: str, scope: Scope, params: dict[str, Any] | None = None) -> Finding:
	"""Execute one analyzer under a resolved scope, with an audit trail."""
	item = get(code)

	if not item.may_run(scope):
		_log(code, scope, permitted=False)
		frappe.throw(
			_("Your role does not permit the analysis '{0}'.").format(item.question),
			frappe.PermissionError,
		)

	finding = item.fn(scope, **(params or {}))

	# Stamped by the registry rather than by each analyzer, so an answer can
	# never be returned without stating the basis it was computed on.
	finding.scope_description = scope.describe()
	finding.as_of = now()

	_log(code, scope, permitted=True)
	return finding


def _log(code: str, scope: Scope, permitted: bool) -> None:
	"""Audit every question, including refused ones.

	Refusals matter more than successes here: repeated refusals are how you
	notice someone probing for data outside their scope.
	"""
	try:
		frappe.get_doc({
			"doctype": "AGS AI Query Log",
			"analyzer": code,
			"asked_by": scope.user,
			"permitted": int(permitted),
			"scope_description": scope.describe(),
			"company": scope.company,
			"campuses": ", ".join(scope.campuses) if scope.campuses else None,
			"unrestricted": int(scope.unrestricted),
		}).insert(ignore_permissions=True)
	except Exception:
		# Never let audit logging break the answer; log and carry on.
		frappe.log_error(
			title="AGS AI: query log failed",
			message=f"{code}\n{frappe.get_traceback()}",
		)


# ---------------------------------------------------------------- utilities
def rank_drivers(current: dict[str, float], previous: dict[str, float],
                 limit: int = 5, minimum_abs: float = 0.0) -> list[Driver]:
	"""Decompose a period-over-period movement into ranked contributors.

	This is the algorithm behind SKILL sec. 28.1's worked output::

	    Revenue        ↓ 4.2%
	    Payroll        ↑ 8.1%
	    Maintenance    ↑ 21%

	``contribution_percent`` is each line's share of the *total absolute*
	movement, not of the total balance. That is the number that answers "why did
	margin move" - a 21% jump on a small maintenance line can matter less than a
	2% drift on payroll, and ranking by percentage change alone hides that.
	"""
	labels = set(current) | set(previous)
	rows: list[Driver] = []

	for label in labels:
		now_value = flt(current.get(label, 0.0))
		then_value = flt(previous.get(label, 0.0))
		change = flt(now_value - then_value, 2)
		# A line that did not move explains nothing. Listing "Rent 0%" among the
		# drivers of a margin change is noise in exactly the place a reader is
		# looking for signal.
		if not change or abs(change) < minimum_abs:
			continue
		change_percent = flt(change / abs(then_value) * 100, 2) if then_value else (
			100.0 if change > 0 else (-100.0 if change < 0 else 0.0)
		)
		rows.append(Driver(
			label=label,
			current=now_value,
			previous=then_value,
			change=change,
			change_percent=change_percent,
			contribution_percent=0.0,
		))

	total_movement = sum(abs(r.change) for r in rows)
	if total_movement:
		for row in rows:
			row.contribution_percent = flt(abs(row.change) / total_movement * 100, 2)

	rows.sort(key=lambda r: abs(r.change), reverse=True)
	return rows[:limit]
